feat: Implement occasions endpoint
NeMaksym/closetdb-server pull request #1
Opened 2023-03-21 21:35 UTC by katrinmelody

2023-03-22 08:25 UTC, NeMaksym requested changes

2023-03-22 08:25 UTC, NeMaksym commented on Controllers/occasionsController.js
> +        item,
- The `item` is undefined
- Let's return nothing for now. Just 200. Later on, I think it may have sense to return the list of occasions

2023-03-22 08:25 UTC, NeMaksym commented on Controllers/occasionsController.js
> +    const newOccasion = await Occasion.create(req.body);
We can't blindly rely on `req.body` because you can't be sure what info someone passes there. I guess we need some kind of validation. 
`If (valid) createOccastion else return error code`

2023-03-22 08:25 UTC, NeMaksym commented on Controllers/occasionsController.js
> +    console.log(occasions);
remove

2023-03-22 15:32 UTC, katrinmelody commented on Controllers/occasionsController.js
> +    const newOccasion = await Occasion.create(req.body);
It doesn't make sense here because the process of creating a new occasion strongly relies on the Occasion Model. Hence you can put wt you want into the req.body, but it won't be included in the new Occasion object as long as these fields aren't declared in the OccasionSchema. 

Regarding the fields that are included in the Schema - both have a status required: true. This means that the request will go through internal Mongoosh validation and a new document will not be created without the missing data

2023-03-22 15:43 UTC, katrinmelody commented on server.js
> +mongoose.set("strictQuery", false);
mongoose.set - sets the strictQuery to false, meaning that you will be allowed to pass in empty queries into any filter( { } ) or sort( { } ) function and it will not return back an error and break your function. This is useful for any functions that return data to users, as in some situations they want to filter and sort it, and sometimes not. So it's a precaution step

2023-03-22 17:57 UTC, NeMaksym commented on Controllers/occasionsController.js
> +    console.log(occasions);
[Because](https://eslint.org/docs/latest/rules/no-console)
Ok, in Node, it says, it isn't considered a bad practice. But there is still no obvious reason to log occasions every time users fetch them. You merge it to the `main` branch, which is a "prod" code.

2023-03-22 18:03 UTC, NeMaksym commented on Controllers/occasionsController.js
> +    const newOccasion = await Occasion.create(req.body);
Ok, so you guarantee it throws a validation error if the wrong data structure passes? If so, we don't handle such error except logging it, but I'm ok with it.

2023-03-22 20:22 UTC, katrinmelody commented on Controllers/occasionsController.js
> +    const newOccasion = await Occasion.create(req.body);
It uses only the data from the fields pre-defined in the Schema. So it doesn't throw the error in case the wrong data is sent - it just ignores it.
But in case there is no required data at all, it will throw a validation error

2023-03-22 20:24 UTC, katrinmelody commented on Controllers/occasionsController.js
> +    console.log(occasions);
So should i delete it or no?

2023-03-22 21:57 UTC, NeMaksym commented on Controllers/occasionsController.js
> +    const newOccasion = await Occasion.create(req.body);
Custom occasions always have `isEveryday === false`, so we can't take it from the body

2023-03-22 22:01 UTC, NeMaksym commented on Controllers/occasionsController.js
> +    console.log(occasions);
It depends on whether there is a reason to keep this line of code here. If yes - keep, if no - delete.

2023-03-23 21:47 UTC, NeMaksym approved these changes

2023-03-23 21:57 UTC, merged